services:
  training-app:
    image: stefanreuter/training-app
    environment:
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KC_CLIENTID: training-app
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KC_CLIENTSECRET: __changeme__
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KC_SCOPE: openid, profile
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KC_ISSUERURI: https://keycloak.traefik.me/realms/training
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KC_USERNAMEATTRIBUTE: preferred_username
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`training.traefik.me`)"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.services.wordpress.loadbalancer.server.port=8080"
      - "traefik.http.services.wordpress.loadbalancer.server.scheme=http"
    restart: on-failure
